
// Context tags to provide additional information for task processing
export type ContextTag = 
  | 'initial_setup'
  | 'user_profile'
  | 'course_context'
  | 'assessment_context'
  | 'feedback_loop'
  | 'adaptation_required'
  | 'system_event'
  | 'learning_path'
  | 'study_plan'
  | 'assessment'
  | 'test'
  | 'quiz'
  | 'content'
  | 'material'
  | 'resources'
  | 'cognitive'
  | 'learning_style'
  | 'feedback'
  | 'review'
  | 'evaluation'
  | 'engagement'
  | 'motivation'
  | 'gamification'
  | 'ui'
  | 'interface'
  | 'display'
  | 'schedule'
  | 'timing'
  | 'planning'
  | 'spaced_repetition'
  | 'flashcard'
  | 'cognitive_profile'
  | 'qualification'
  | 'adaptive'
  | 'difficulty'
  | 'optimization'
  | 'flashcards';

// Remove duplicate TaskStatus export since it's already defined in agentTypes.ts
// export type TaskStatus = 'pending' | 'processing' | 'completed' | 'failed';
