
// Types for the multi-agent system

export enum TaskTypes {
  LEARNING_PATH_GENERATION = 'LEARNING_PATH_GENERATION',
  COGNITIVE_PROFILING = 'COGNITIVE_PROFILING',
  SCHEDULE_OPTIMIZATION = 'SCHEDULE_OPTIMIZATION',
  ASSESSMENT_GENERATION = 'ASSESSMENT_GENERATION'
}
